## Numpy

In [1]:
import numpy as np

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
## Create array using Numpy
## create a 1d array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
print(type(arr1))

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row 5 coulmns

array([[1, 2, 3, 4, 5]])

In [11]:
## 2D Array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [15]:
np.arange(0,10).reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
## identity matirx
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
## Nunmpy Vectorized Opreation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

### Element Wise addition
print("Addition",arr1+arr2)

### Element Wise Subtraction
print(arr2-arr1)

Addition [11 22 33 44 55]
[ 9 18 27 36 45]


In [22]:
## Universal Function
arr1 = np.array([1,2,3,4,5])
## square root
print(np.sqrt(arr1))

## Exponential
print(np.exp(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [25]:
## array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
arr[0][3]

np.int64(4)

In [32]:
arr[1:,3:]

array([[ 8],
       [12]])

In [35]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [37]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [38]:
## Modify elements
arr[0][0] =100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [39]:
arr[1:] =100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [40]:
## Practical application -- Normalization
## to have a mean of 0 and standard devitaion of 1

data = np.array([1,2,3,4,5])
## Calculate the mean and standard deviation 
mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data-mean)/std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [42]:
## Median
men = np.median(data)
print(men)
mean_data = np.mean(data)
print(mean_data)
variance = np.var(data)
print(variance)

3.0
3.0
2.0


In [49]:
## Logical Opreation 
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=9)]

array([5, 6, 7, 8, 9])

## Pandas

In [50]:
import pandas as pd